premake: Fix the VST2 boilerplate cpp-files inside the VST3 SDK
VST2 boileplate cpp-files inside the VST3 SDK had an incorrect path,
which went silent from the build system.  Enumerate the needed
boilerplate cpp-files explicitly so that the build system will always
give us an error if any of the files are missing.

However, comment the files out because compiling vst2wrapper.cpp will
result the following compiler error (Linux/GCC):

vst3sdk/public.sdk/source/vst/basewrapper/basewrapper.cpp: In member function ‘virtual bool Steinberg::Vst::BaseEditorWrapper::_open(void*)’:
vst3sdk/public.sdk/source/vst/basewrapper/basewrapper.cpp:197:32: error: ‘type’ was not declared in this scope
   return mView->attached (ptr, type) == kResultTrue;

Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@iki.fi>